version: '3.7'

services:
  mysql-master:
    platform: 'linux/amd64'
    build: ./mysql/replication/v57/master
    container_name: ${PROJECT_NAME}-mysql-master
    volumes:
      - local-db-store:/var/lib/mysql # データの永続化
      - ./mysql/replication/v57/master/sql:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_MASTER_PORT}:3306"
    environment:
      DB_USER: ${DB_USER}
      DB_DATABASE: ${DB_REPLICATION_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"

  mysql-slave:
    platform: 'linux/amd64'
    build: ./mysql/replication/v57/slave
    container_name: ${PROJECT_NAME}-mysql-slave
    ports:
      - "${MYSQL_SLAVE_PORT}:3306"
    depends_on:
      - mysql-master
    volumes:
      - local-db-store-slave:/var/lib/mysql # データの永続化
      - ./mysql/replication/v57/slave/sql:/docker-entrypoint-initdb.d
    environment:
      DB_USER: ${DB_USER}
      DB_DATABASE: ${DB_REPLICATION_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"

volumes:
  local-db-store:
    name: ${VOLUME_NAME_REPLICATION_V57}
    # driver: local
    external: true
  local-db-store-slave:
    name: ${VOLUME_NAME_REPLICATION_V57}-slave
    # driver: local
    external: true
