version: '3.7'

services:
  mysql-db:
    build: ./mysql
    container_name: ${PROJECT_NAME}_db
    volumes:
      - local-db-store:/var/lib/mysql # データの永続化
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"

volumes:
  local-db-store:
    name: ${VOLUME_NAME}
    driver: local
