CREATE DATABASE IF NOT EXISTS local_db_replication CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON local_db.* TO 'root'@'%';

FLUSH PRIVILEGES;

-- レプリケーション用ユーザの作成
CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED BY 'password';
GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';

FLUSH PRIVILEGES;
